apiVersion: restart.jgiornazi.dev/v1alpha1
kind: ScheduledRestart
metadata:
  labels:
    app.kubernetes.io/name: k8s-podrestart-operator
    app.kubernetes.io/managed-by: kustomize
  name: scheduledrestart-sample
spec:
  # TODO(user): Add fields here
  selector:
    matchLabels:
      app: test-app
  schedule: "*/2 * * * *"
  suspend: False
  restartPolicy: RollingDelete
